apiVersion: v1
kind: Service
metadata:
  name: content-api
spec:
  selector:
    app: hacker-api
    version: green
  ports:
    - protocol: TCP
      port: 3001           # The port your app will use to connect
      targetPort: 3001    # The port the web application is listening on inside the pod