apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017         # The port your app will use to connect
      targetPort: 27017   # The port MongoDB is listening on inside the pod