apiVersion: apps/v1
kind: Deployment
metadata:
  name: hacker-web-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hacker-web-green
  template:
    metadata:
      labels:
        app: hacker-web-green
        version: green
    spec:
      containers:
      - name: api-container
        image: hackcontainerregistry.azurecr.io/hacker-web:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"