apiVersion: apps/v1
kind: Deployment
metadata:
  name: hacker-web-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hacker-web
  template:
    metadata:
      labels:
        app: hacker-web
        version: green
    spec:
      containers:
      - name: api-container
        image: whatthehackmsft/content-web:v2
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"