apiVersion: v1
kind: Service
metadata:
  name: hacker-web-service-green
spec:
  selector:
    app: hacker-web-green
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80            # The port your app will use to connect
      targetPort: 3000    # The port the web application is listening on inside the pod