apiVersion: apps/v1
kind: Deployment
metadata:
  name: hacker-api-blue
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hacker-api
  template:
    metadata:
      labels:
        app: hacker-api
        version: blue
    spec:
      containers:
      - name: api-container
        image: hackcontainerregistry.azurecr.io/hacker-api:latest
        env:
        - name: MONGODB_CONNECTION
          value: mongodb://mongo:27017/contentdb
        ports:
        - containerPort: 3001
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"